liip_imagine:
    driver: "gd"
    filter_sets:
        test:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                thumbnail: { size: [250, 250], mode: outbound, allow_upscale: false}
