<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211202171711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access (id INT AUTO_INCREMENT NOT NULL, a_label VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE address (id INT AUTO_INCREMENT NOT NULL, way VARCHAR(250) DEFAULT NULL, pc VARCHAR(10) DEFAULT NULL, city VARCHAR(30) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, user_admin_id INT NOT NULL, state_id INT NOT NULL, access_id INT DEFAULT NULL, thematic_id INT NOT NULL, category_id INT NOT NULL, art_name VARCHAR(120) NOT NULL, description LONGTEXT NOT NULL, art_img VARCHAR(255) DEFAULT NULL, creation_date DATE NOT NULL, exp_date DATE DEFAULT NULL, short_description VARCHAR(255) DEFAULT NULL, nb_of_view INT NOT NULL, INDEX IDX_23A0E6684A66610 (user_admin_id), INDEX IDX_23A0E665D83CC1 (state_id), INDEX IDX_23A0E664FEA67CF (access_id), INDEX IDX_23A0E662395FCED (thematic_id), INDEX IDX_23A0E6612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE audit (id INT AUTO_INCREMENT NOT NULL, part_one_id INT NOT NULL, part_two_id INT DEFAULT NULL, part_three_id INT DEFAULT NULL, part_four_id INT DEFAULT NULL, part_five_id INT DEFAULT NULL, part_six_id INT DEFAULT NULL, part_seven_id INT DEFAULT NULL, user_id INT DEFAULT NULL, creation_date DATE NOT NULL, enclose_date DATE DEFAULT NULL, progress INT NOT NULL, INDEX IDX_9218FF79C20A0E86 (part_one_id), INDEX IDX_9218FF79A956E949 (part_two_id), INDEX IDX_9218FF79E0F3881A (part_three_id), INDEX IDX_9218FF7965F0F7AF (part_four_id), INDEX IDX_9218FF7939C70144 (part_five_id), INDEX IDX_9218FF79A64D9F34 (part_six_id), INDEX IDX_9218FF79C77125D4 (part_seven_id), INDEX IDX_9218FF79A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, access_id INT DEFAULT NULL, cat_label VARCHAR(20) NOT NULL, INDEX IDX_64C19C14FEA67CF (access_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE children (id INT AUTO_INCREMENT NOT NULL, yob INT DEFAULT NULL, handicapped TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collective_foresight (id INT AUTO_INCREMENT NOT NULL, cf_label VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collective_retirement (id INT AUTO_INCREMENT NOT NULL, collective_retirement_label VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, article_id INT NOT NULL, comment LONGTEXT NOT NULL, INDEX IDX_9474526CA76ED395 (user_id), INDEX IDX_9474526C7294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE credit_leasing (id INT AUTO_INCREMENT NOT NULL, total_remaining INT DEFAULT NULL, end DATE DEFAULT NULL, rate VARCHAR(15) DEFAULT NULL, mensuality INT DEFAULT NULL, cover_first_insured INT DEFAULT NULL, cover_second_insured INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE death_funds (id INT AUTO_INCREMENT NOT NULL, consumption TINYINT(1) DEFAULT NULL, acquisition TINYINT(1) DEFAULT NULL, amount_acquisition INT DEFAULT NULL, investment TINYINT(1) DEFAULT NULL, amount_investment INT DEFAULT NULL, preference TINYINT(1) DEFAULT NULL, preference_name VARCHAR(120) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documents (id INT AUTO_INCREMENT NOT NULL, document VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE drop_reaction (id INT AUTO_INCREMENT NOT NULL, drop_label VARCHAR(55) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evolution (id INT AUTO_INCREMENT NOT NULL, pro_status_id INT DEFAULT NULL, salary_id INT DEFAULT NULL, evolution_choice TINYINT(1) NOT NULL, year INT DEFAULT NULL, INDEX IDX_420C28937B3C8E45 (pro_status_id), INDEX IDX_420C2893B0FDF16E (salary_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE family_needs (id INT AUTO_INCREMENT NOT NULL, funeral INT NOT NULL, income_taxes INT NOT NULL, property_taxes INT NOT NULL, housing_taxes INT NOT NULL, torew INT NOT NULL, professional_load INT NOT NULL, corporate_taxes INT NOT NULL, professional_vehicle TINYINT(1) NOT NULL, spouse_additional_capital INT NOT NULL, other_additional_capital INT NOT NULL, spouse_salary INT NOT NULL, sufficient_salary TINYINT(1) NOT NULL, wwdc TINYINT(1) NOT NULL, missing_monthly_income INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financial_investment (id INT AUTO_INCREMENT NOT NULL, fi_label VARCHAR(90) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financial_products (id INT AUTO_INCREMENT NOT NULL, nothing TINYINT(1) DEFAULT NULL, bank_account TINYINT(1) DEFAULT NULL, financial_savings TINYINT(1) DEFAULT NULL, life_insurance TINYINT(1) DEFAULT NULL, life_insurance_uc INT DEFAULT NULL, retirement_investment TINYINT(1) DEFAULT NULL, retirement_investment_uc INT DEFAULT NULL, employee_savings TINYINT(1) DEFAULT NULL, employee_savings_uc INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE future_income (id INT AUTO_INCREMENT NOT NULL, pro_status_id INT DEFAULT NULL, salary_id INT DEFAULT NULL, year_label VARCHAR(15) NOT NULL, INDEX IDX_5EB9C5E97B3C8E45 (pro_status_id), INDEX IDX_5EB9C5E9B0FDF16E (salary_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gender (id INT AUTO_INCREMENT NOT NULL, glabel VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE guarantee (id INT AUTO_INCREMENT NOT NULL, guarantee_label_id INT NOT NULL, company VARCHAR(120) DEFAULT NULL, amount_of_guarantees INT DEFAULT NULL, date DATE DEFAULT NULL, contribution INT DEFAULT NULL, madelin TINYINT(1) NOT NULL, beneficiaries VARCHAR(120) DEFAULT NULL, INDEX IDX_589198D8E7A1D12E (guarantee_label_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE guarantee_label (id INT AUTO_INCREMENT NOT NULL, guarantee_label VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE health_needs (id INT AUTO_INCREMENT NOT NULL, mutual_health_satisfaction TINYINT(1) NOT NULL, glasses TINYINT(1) NOT NULL, dental_care TINYINT(1) NOT NULL, fee_overruns TINYINT(1) NOT NULL, not_reimbursed TINYINT(1) NOT NULL, spa_treatment TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE individual_form (id INT AUTO_INCREMENT NOT NULL, financial_products_id INT NOT NULL, previous_financial_products_id INT NOT NULL, financial_investment_id INT NOT NULL, risk_id INT NOT NULL, share_of_investment_id INT NOT NULL, unplanned_id INT NOT NULL, drop_reaction_id INT NOT NULL, preference_id INT NOT NULL, death_funds_id INT DEFAULT NULL, INDEX IDX_9A4A67FC2EBD7B35 (financial_products_id), INDEX IDX_9A4A67FC36A17427 (previous_financial_products_id), INDEX IDX_9A4A67FCEE87D3F6 (financial_investment_id), INDEX IDX_9A4A67FC235B6D1 (risk_id), INDEX IDX_9A4A67FC328E815D (share_of_investment_id), INDEX IDX_9A4A67FC200761 (unplanned_id), INDEX IDX_9A4A67FC6BF8A3D3 (drop_reaction_id), INDEX IDX_9A4A67FCD81022C0 (preference_id), INDEX IDX_9A4A67FCD3D321CA (death_funds_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intelligence (id INT AUTO_INCREMENT NOT NULL, woman TINYINT(1) NOT NULL, man TINYINT(1) NOT NULL, name VARCHAR(120) NOT NULL, firstname VARCHAR(120) NOT NULL, phone VARCHAR(15) NOT NULL, email VARCHAR(50) NOT NULL, native_country VARCHAR(60) NOT NULL, department VARCHAR(25) NOT NULL, job VARCHAR(120) NOT NULL, compagny_form VARCHAR(25) DEFAULT NULL, axa_customer TINYINT(1) NOT NULL, social_security_number BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maried (id INT AUTO_INCREMENT NOT NULL, community_before TINYINT(1) NOT NULL, community_after TINYINT(1) NOT NULL, separation_of_property TINYINT(1) NOT NULL, part_acquisitions TINYINT(1) NOT NULL, year INT DEFAULT NULL, previous_wedding TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movable_heritage (id INT AUTO_INCREMENT NOT NULL, movable_heritage_label_id INT NOT NULL, detained_by VARCHAR(120) DEFAULT NULL, open_date DATE DEFAULT NULL, amount INT DEFAULT NULL, organization VARCHAR(120) DEFAULT NULL, interest_rate INT DEFAULT NULL, monthly_annual_payment VARCHAR(50) DEFAULT NULL, goal VARCHAR(120) DEFAULT NULL, beneficiary VARCHAR(120) DEFAULT NULL, INDEX IDX_BD28D1F77F5FC5D8 (movable_heritage_label_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movable_heritage_label (id INT AUTO_INCREMENT NOT NULL, movable_heritage_label VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE objective (id INT AUTO_INCREMENT NOT NULL, audit TINYINT(1) NOT NULL, retirement_solution TINYINT(1) NOT NULL, succession_solution TINYINT(1) NOT NULL, foresight_solution TINYINT(1) NOT NULL, saving_solution TINYINT(1) NOT NULL, health_solution TINYINT(1) NOT NULL, tax_solution TINYINT(1) NOT NULL, borrower_insurance TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_five (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_five_individual_form (part_five_id INT NOT NULL, individual_form_id INT NOT NULL, INDEX IDX_1935577439C70144 (part_five_id), INDEX IDX_19355774662A1AF0 (individual_form_id), PRIMARY KEY(part_five_id, individual_form_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_four (id INT AUTO_INCREMENT NOT NULL, main_bank VARCHAR(120) NOT NULL, satisfaction TINYINT(1) NOT NULL, advice_frequency TINYINT(1) NOT NULL, missing_service VARCHAR(250) NOT NULL, monthly_saving INT NOT NULL, open_to_proposals TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_four_movable_heritage (part_four_id INT NOT NULL, movable_heritage_id INT NOT NULL, INDEX IDX_B630E8D565F0F7AF (part_four_id), INDEX IDX_B630E8D57B5CFC7C (movable_heritage_id), PRIMARY KEY(part_four_id, movable_heritage_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_one (id INT AUTO_INCREMENT NOT NULL, objective_id INT NOT NULL, intelligence_id INT NOT NULL, share_in_company_id INT DEFAULT NULL, status_id INT NOT NULL, maried_id INT DEFAULT NULL, pro_status_id INT NOT NULL, donation TINYINT(1) NOT NULL, testament TINYINT(1) NOT NULL, notary TINYINT(1) NOT NULL, notary_name VARCHAR(120) DEFAULT NULL, donation_between_spouses TINYINT(1) NOT NULL, child TINYINT(1) NOT NULL, INDEX IDX_B848A37A73484933 (objective_id), INDEX IDX_B848A37A7584E372 (intelligence_id), INDEX IDX_B848A37A8AFB327A (share_in_company_id), INDEX IDX_B848A37A6BF700BD (status_id), INDEX IDX_B848A37A7FFEC9A3 (maried_id), INDEX IDX_B848A37A7B3C8E45 (pro_status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_one_children (part_one_id INT NOT NULL, children_id INT NOT NULL, INDEX IDX_4F65F7F8C20A0E86 (part_one_id), INDEX IDX_4F65F7F83D3D2749 (children_id), PRIMARY KEY(part_one_id, children_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_seven (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_seven_documents (part_seven_id INT NOT NULL, documents_id INT NOT NULL, INDEX IDX_5A718CF5C77125D4 (part_seven_id), INDEX IDX_5A718CF55F0F2752 (documents_id), PRIMARY KEY(part_seven_id, documents_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_six (id INT AUTO_INCREMENT NOT NULL, family_needs_id INT NOT NULL, health_needs_id INT NOT NULL, single_min_income INT NOT NULL, couple_min_income INT NOT NULL, stop_working INT NOT NULL, retirement_capital TINYINT(1) NOT NULL, amount_retirement_capital INT DEFAULT NULL, medical_history TINYINT(1) NOT NULL, family_medical_history TINYINT(1) NOT NULL, smoking TINYINT(1) NOT NULL, stop_smoking TINYINT(1) DEFAULT NULL, cover TINYINT(1) NOT NULL, comment VARCHAR(250) NOT NULL, have_reco TINYINT(1) NOT NULL, INDEX IDX_813303706F76B9E5 (family_needs_id), INDEX IDX_8133037045E92F38 (health_needs_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_six_recommendation (part_six_id INT NOT NULL, recommendation_id INT NOT NULL, INDEX IDX_A4A72444A64D9F34 (part_six_id), INDEX IDX_A4A72444D173940B (recommendation_id), PRIMARY KEY(part_six_id, recommendation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_three (id INT AUTO_INCREMENT NOT NULL, have_credit_leasing TINYINT(1) NOT NULL, project TINYINT(1) NOT NULL, needs VARCHAR(250) DEFAULT NULL, trusted_lawyer TINYINT(1) NOT NULL, legal_specificity VARCHAR(250) DEFAULT NULL, law_firm VARCHAR(250) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_three_patrimony (part_three_id INT NOT NULL, patrimony_id INT NOT NULL, INDEX IDX_AFC67A0CE0F3881A (part_three_id), INDEX IDX_AFC67A0C9A60D1F0 (patrimony_id), PRIMARY KEY(part_three_id, patrimony_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_three_credit_leasing (part_three_id INT NOT NULL, credit_leasing_id INT NOT NULL, INDEX IDX_AD5E0BE4E0F3881A (part_three_id), INDEX IDX_AD5E0BE43A14DD68 (credit_leasing_id), PRIMARY KEY(part_three_id, credit_leasing_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_two (id INT AUTO_INCREMENT NOT NULL, collective_foresight_id INT DEFAULT NULL, savings_plan_id INT DEFAULT NULL, collective_retirement_id INT DEFAULT NULL, evolution_id INT DEFAULT NULL, salary_id INT NOT NULL, active_company_savings_plan TINYINT(1) DEFAULT NULL, actual_saving INT DEFAULT NULL, contribution_class TINYINT(1) NOT NULL, contribution_class_label VARCHAR(15) DEFAULT NULL, trusted_account TINYINT(1) NOT NULL, trusted_account_name VARCHAR(120) DEFAULT NULL, able_to_measure VARCHAR(15) NOT NULL, INDEX IDX_D3EEAFED81CAE112 (collective_foresight_id), INDEX IDX_D3EEAFED7F8E4905 (savings_plan_id), INDEX IDX_D3EEAFED97F4F26A (collective_retirement_id), INDEX IDX_D3EEAFEDCDFF215A (evolution_id), INDEX IDX_D3EEAFEDB0FDF16E (salary_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_two_guarantee (part_two_id INT NOT NULL, guarantee_id INT NOT NULL, INDEX IDX_E07DDCB2A956E949 (part_two_id), INDEX IDX_E07DDCB2DB4B0220 (guarantee_id), PRIMARY KEY(part_two_id, guarantee_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_two_future_income (part_two_id INT NOT NULL, future_income_id INT NOT NULL, INDEX IDX_4AC070CCA956E949 (part_two_id), INDEX IDX_4AC070CCC4420662 (future_income_id), PRIMARY KEY(part_two_id, future_income_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE part_two_total_annual_income (part_two_id INT NOT NULL, total_annual_income_id INT NOT NULL, INDEX IDX_B9EAAD0FA956E949 (part_two_id), INDEX IDX_B9EAAD0F81AC812C (total_annual_income_id), PRIMARY KEY(part_two_id, total_annual_income_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE patrimony (id INT AUTO_INCREMENT NOT NULL, patrimony_label_id INT NOT NULL, detained_by VARCHAR(120) DEFAULT NULL, method_of_detention VARCHAR(15) DEFAULT NULL, estimated_value INT DEFAULT NULL, acquisition_value INT DEFAULT NULL, taxation VARCHAR(120) DEFAULT NULL, rent INT DEFAULT NULL, sale TINYINT(1) DEFAULT NULL, capital_of_rest INT DEFAULT NULL, lender VARCHAR(120) DEFAULT NULL, borrowing_date DATE DEFAULT NULL, during INT DEFAULT NULL, percentage_of_insurance VARCHAR(15) DEFAULT NULL, rate VARCHAR(15) DEFAULT NULL, INDEX IDX_986416E23DA10740 (patrimony_label_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE patrimony_label (id INT AUTO_INCREMENT NOT NULL, patrimony_label VARCHAR(30) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE preference (id INT AUTO_INCREMENT NOT NULL, pref_label VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE previous_financial_products (id INT AUTO_INCREMENT NOT NULL, pfp_label VARCHAR(30) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pro_status (id INT AUTO_INCREMENT NOT NULL, pro_label VARCHAR(60) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recommendation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT NULL, firstname VARCHAR(120) DEFAULT NULL, job VARCHAR(120) DEFAULT NULL, age INT DEFAULT NULL, relationship VARCHAR(50) DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, mail VARCHAR(50) DEFAULT NULL, calling_times VARCHAR(120) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE risk (id INT AUTO_INCREMENT NOT NULL, risk_label VARCHAR(35) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salary (id INT AUTO_INCREMENT NOT NULL, amount INT DEFAULT NULL, gross_net TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE savings_plan (id INT AUTO_INCREMENT NOT NULL, savings_label VARCHAR(25) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share_in_compagny (id INT AUTO_INCREMENT NOT NULL, share_label VARCHAR(15) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share_of_investment (id INT AUTO_INCREMENT NOT NULL, soi_label VARCHAR(15) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE state (id INT AUTO_INCREMENT NOT NULL, state_label VARCHAR(8) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE status (id INT AUTO_INCREMENT NOT NULL, s_label VARCHAR(12) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE thematic (id INT AUTO_INCREMENT NOT NULL, th_label VARCHAR(25) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE total_annual_income (id INT AUTO_INCREMENT NOT NULL, salary_id INT DEFAULT NULL, income_label VARCHAR(50) DEFAULT NULL, INDEX IDX_3BB45A54B0FDF16E (salary_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unplanned (id INT AUTO_INCREMENT NOT NULL, unpl_label VARCHAR(90) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, gender_id INT DEFAULT NULL, address_id INT DEFAULT NULL, status_id INT DEFAULT NULL, img VARCHAR(255) DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, firstname VARCHAR(120) DEFAULT NULL, pseudo VARCHAR(20) NOT NULL, pwd VARCHAR(255) NOT NULL, birthday DATE DEFAULT NULL, email VARCHAR(50) NOT NULL, phone VARCHAR(15) DEFAULT NULL, mobile VARCHAR(15) DEFAULT NULL, mutual_health TINYINT(1) DEFAULT NULL, retirement TINYINT(1) DEFAULT NULL, foresight TINYINT(1) DEFAULT NULL, tax TINYINT(1) DEFAULT NULL, saving TINYINT(1) DEFAULT NULL, succession TINYINT(1) DEFAULT NULL, admin TINYINT(1) DEFAULT NULL, newsletter TINYINT(1) NOT NULL, partner_offers TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8D93D64986CC499D (pseudo), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D649708A0E0 (gender_id), INDEX IDX_8D93D649F5B7AF75 (address_id), INDEX IDX_8D93D6496BF700BD (status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6684A66610 FOREIGN KEY (user_admin_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E665D83CC1 FOREIGN KEY (state_id) REFERENCES state (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E664FEA67CF FOREIGN KEY (access_id) REFERENCES access (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E662395FCED FOREIGN KEY (thematic_id) REFERENCES thematic (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79C20A0E86 FOREIGN KEY (part_one_id) REFERENCES part_one (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79A956E949 FOREIGN KEY (part_two_id) REFERENCES part_two (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79E0F3881A FOREIGN KEY (part_three_id) REFERENCES part_three (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF7965F0F7AF FOREIGN KEY (part_four_id) REFERENCES part_four (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF7939C70144 FOREIGN KEY (part_five_id) REFERENCES part_five (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79A64D9F34 FOREIGN KEY (part_six_id) REFERENCES part_six (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79C77125D4 FOREIGN KEY (part_seven_id) REFERENCES part_seven (id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C14FEA67CF FOREIGN KEY (access_id) REFERENCES access (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C7294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE evolution ADD CONSTRAINT FK_420C28937B3C8E45 FOREIGN KEY (pro_status_id) REFERENCES pro_status (id)');
        $this->addSql('ALTER TABLE evolution ADD CONSTRAINT FK_420C2893B0FDF16E FOREIGN KEY (salary_id) REFERENCES salary (id)');
        $this->addSql('ALTER TABLE future_income ADD CONSTRAINT FK_5EB9C5E97B3C8E45 FOREIGN KEY (pro_status_id) REFERENCES pro_status (id)');
        $this->addSql('ALTER TABLE future_income ADD CONSTRAINT FK_5EB9C5E9B0FDF16E FOREIGN KEY (salary_id) REFERENCES salary (id)');
        $this->addSql('ALTER TABLE guarantee ADD CONSTRAINT FK_589198D8E7A1D12E FOREIGN KEY (guarantee_label_id) REFERENCES guarantee_label (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FC2EBD7B35 FOREIGN KEY (financial_products_id) REFERENCES financial_products (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FC36A17427 FOREIGN KEY (previous_financial_products_id) REFERENCES previous_financial_products (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FCEE87D3F6 FOREIGN KEY (financial_investment_id) REFERENCES financial_investment (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FC235B6D1 FOREIGN KEY (risk_id) REFERENCES risk (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FC328E815D FOREIGN KEY (share_of_investment_id) REFERENCES share_of_investment (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FC200761 FOREIGN KEY (unplanned_id) REFERENCES unplanned (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FC6BF8A3D3 FOREIGN KEY (drop_reaction_id) REFERENCES drop_reaction (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FCD81022C0 FOREIGN KEY (preference_id) REFERENCES preference (id)');
        $this->addSql('ALTER TABLE individual_form ADD CONSTRAINT FK_9A4A67FCD3D321CA FOREIGN KEY (death_funds_id) REFERENCES death_funds (id)');
        $this->addSql('ALTER TABLE movable_heritage ADD CONSTRAINT FK_BD28D1F77F5FC5D8 FOREIGN KEY (movable_heritage_label_id) REFERENCES movable_heritage_label (id)');
        $this->addSql('ALTER TABLE part_five_individual_form ADD CONSTRAINT FK_1935577439C70144 FOREIGN KEY (part_five_id) REFERENCES part_five (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_five_individual_form ADD CONSTRAINT FK_19355774662A1AF0 FOREIGN KEY (individual_form_id) REFERENCES individual_form (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_four_movable_heritage ADD CONSTRAINT FK_B630E8D565F0F7AF FOREIGN KEY (part_four_id) REFERENCES part_four (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_four_movable_heritage ADD CONSTRAINT FK_B630E8D57B5CFC7C FOREIGN KEY (movable_heritage_id) REFERENCES movable_heritage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_one ADD CONSTRAINT FK_B848A37A73484933 FOREIGN KEY (objective_id) REFERENCES objective (id)');
        $this->addSql('ALTER TABLE part_one ADD CONSTRAINT FK_B848A37A7584E372 FOREIGN KEY (intelligence_id) REFERENCES intelligence (id)');
        $this->addSql('ALTER TABLE part_one ADD CONSTRAINT FK_B848A37A8AFB327A FOREIGN KEY (share_in_company_id) REFERENCES share_in_compagny (id)');
        $this->addSql('ALTER TABLE part_one ADD CONSTRAINT FK_B848A37A6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE part_one ADD CONSTRAINT FK_B848A37A7FFEC9A3 FOREIGN KEY (maried_id) REFERENCES maried (id)');
        $this->addSql('ALTER TABLE part_one ADD CONSTRAINT FK_B848A37A7B3C8E45 FOREIGN KEY (pro_status_id) REFERENCES pro_status (id)');
        $this->addSql('ALTER TABLE part_one_children ADD CONSTRAINT FK_4F65F7F8C20A0E86 FOREIGN KEY (part_one_id) REFERENCES part_one (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_one_children ADD CONSTRAINT FK_4F65F7F83D3D2749 FOREIGN KEY (children_id) REFERENCES children (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_seven_documents ADD CONSTRAINT FK_5A718CF5C77125D4 FOREIGN KEY (part_seven_id) REFERENCES part_seven (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_seven_documents ADD CONSTRAINT FK_5A718CF55F0F2752 FOREIGN KEY (documents_id) REFERENCES documents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_six ADD CONSTRAINT FK_813303706F76B9E5 FOREIGN KEY (family_needs_id) REFERENCES family_needs (id)');
        $this->addSql('ALTER TABLE part_six ADD CONSTRAINT FK_8133037045E92F38 FOREIGN KEY (health_needs_id) REFERENCES health_needs (id)');
        $this->addSql('ALTER TABLE part_six_recommendation ADD CONSTRAINT FK_A4A72444A64D9F34 FOREIGN KEY (part_six_id) REFERENCES part_six (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_six_recommendation ADD CONSTRAINT FK_A4A72444D173940B FOREIGN KEY (recommendation_id) REFERENCES recommendation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_three_patrimony ADD CONSTRAINT FK_AFC67A0CE0F3881A FOREIGN KEY (part_three_id) REFERENCES part_three (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_three_patrimony ADD CONSTRAINT FK_AFC67A0C9A60D1F0 FOREIGN KEY (patrimony_id) REFERENCES patrimony (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_three_credit_leasing ADD CONSTRAINT FK_AD5E0BE4E0F3881A FOREIGN KEY (part_three_id) REFERENCES part_three (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_three_credit_leasing ADD CONSTRAINT FK_AD5E0BE43A14DD68 FOREIGN KEY (credit_leasing_id) REFERENCES credit_leasing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_two ADD CONSTRAINT FK_D3EEAFED81CAE112 FOREIGN KEY (collective_foresight_id) REFERENCES collective_foresight (id)');
        $this->addSql('ALTER TABLE part_two ADD CONSTRAINT FK_D3EEAFED7F8E4905 FOREIGN KEY (savings_plan_id) REFERENCES savings_plan (id)');
        $this->addSql('ALTER TABLE part_two ADD CONSTRAINT FK_D3EEAFED97F4F26A FOREIGN KEY (collective_retirement_id) REFERENCES collective_retirement (id)');
        $this->addSql('ALTER TABLE part_two ADD CONSTRAINT FK_D3EEAFEDCDFF215A FOREIGN KEY (evolution_id) REFERENCES evolution (id)');
        $this->addSql('ALTER TABLE part_two ADD CONSTRAINT FK_D3EEAFEDB0FDF16E FOREIGN KEY (salary_id) REFERENCES salary (id)');
        $this->addSql('ALTER TABLE part_two_guarantee ADD CONSTRAINT FK_E07DDCB2A956E949 FOREIGN KEY (part_two_id) REFERENCES part_two (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_two_guarantee ADD CONSTRAINT FK_E07DDCB2DB4B0220 FOREIGN KEY (guarantee_id) REFERENCES guarantee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_two_future_income ADD CONSTRAINT FK_4AC070CCA956E949 FOREIGN KEY (part_two_id) REFERENCES part_two (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_two_future_income ADD CONSTRAINT FK_4AC070CCC4420662 FOREIGN KEY (future_income_id) REFERENCES future_income (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_two_total_annual_income ADD CONSTRAINT FK_B9EAAD0FA956E949 FOREIGN KEY (part_two_id) REFERENCES part_two (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE part_two_total_annual_income ADD CONSTRAINT FK_B9EAAD0F81AC812C FOREIGN KEY (total_annual_income_id) REFERENCES total_annual_income (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE patrimony ADD CONSTRAINT FK_986416E23DA10740 FOREIGN KEY (patrimony_label_id) REFERENCES patrimony_label (id)');
        $this->addSql('ALTER TABLE total_annual_income ADD CONSTRAINT FK_3BB45A54B0FDF16E FOREIGN KEY (salary_id) REFERENCES salary (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6496BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E664FEA67CF');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C14FEA67CF');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F5B7AF75');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526C7294869C');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E6612469DE2');
        $this->addSql('ALTER TABLE part_one_children DROP FOREIGN KEY FK_4F65F7F83D3D2749');
        $this->addSql('ALTER TABLE part_two DROP FOREIGN KEY FK_D3EEAFED81CAE112');
        $this->addSql('ALTER TABLE part_two DROP FOREIGN KEY FK_D3EEAFED97F4F26A');
        $this->addSql('ALTER TABLE part_three_credit_leasing DROP FOREIGN KEY FK_AD5E0BE43A14DD68');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FCD3D321CA');
        $this->addSql('ALTER TABLE part_seven_documents DROP FOREIGN KEY FK_5A718CF55F0F2752');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FC6BF8A3D3');
        $this->addSql('ALTER TABLE part_two DROP FOREIGN KEY FK_D3EEAFEDCDFF215A');
        $this->addSql('ALTER TABLE part_six DROP FOREIGN KEY FK_813303706F76B9E5');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FCEE87D3F6');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FC2EBD7B35');
        $this->addSql('ALTER TABLE part_two_future_income DROP FOREIGN KEY FK_4AC070CCC4420662');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649708A0E0');
        $this->addSql('ALTER TABLE part_two_guarantee DROP FOREIGN KEY FK_E07DDCB2DB4B0220');
        $this->addSql('ALTER TABLE guarantee DROP FOREIGN KEY FK_589198D8E7A1D12E');
        $this->addSql('ALTER TABLE part_six DROP FOREIGN KEY FK_8133037045E92F38');
        $this->addSql('ALTER TABLE part_five_individual_form DROP FOREIGN KEY FK_19355774662A1AF0');
        $this->addSql('ALTER TABLE part_one DROP FOREIGN KEY FK_B848A37A7584E372');
        $this->addSql('ALTER TABLE part_one DROP FOREIGN KEY FK_B848A37A7FFEC9A3');
        $this->addSql('ALTER TABLE part_four_movable_heritage DROP FOREIGN KEY FK_B630E8D57B5CFC7C');
        $this->addSql('ALTER TABLE movable_heritage DROP FOREIGN KEY FK_BD28D1F77F5FC5D8');
        $this->addSql('ALTER TABLE part_one DROP FOREIGN KEY FK_B848A37A73484933');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF7939C70144');
        $this->addSql('ALTER TABLE part_five_individual_form DROP FOREIGN KEY FK_1935577439C70144');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF7965F0F7AF');
        $this->addSql('ALTER TABLE part_four_movable_heritage DROP FOREIGN KEY FK_B630E8D565F0F7AF');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF79C20A0E86');
        $this->addSql('ALTER TABLE part_one_children DROP FOREIGN KEY FK_4F65F7F8C20A0E86');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF79C77125D4');
        $this->addSql('ALTER TABLE part_seven_documents DROP FOREIGN KEY FK_5A718CF5C77125D4');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF79A64D9F34');
        $this->addSql('ALTER TABLE part_six_recommendation DROP FOREIGN KEY FK_A4A72444A64D9F34');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF79E0F3881A');
        $this->addSql('ALTER TABLE part_three_patrimony DROP FOREIGN KEY FK_AFC67A0CE0F3881A');
        $this->addSql('ALTER TABLE part_three_credit_leasing DROP FOREIGN KEY FK_AD5E0BE4E0F3881A');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF79A956E949');
        $this->addSql('ALTER TABLE part_two_guarantee DROP FOREIGN KEY FK_E07DDCB2A956E949');
        $this->addSql('ALTER TABLE part_two_future_income DROP FOREIGN KEY FK_4AC070CCA956E949');
        $this->addSql('ALTER TABLE part_two_total_annual_income DROP FOREIGN KEY FK_B9EAAD0FA956E949');
        $this->addSql('ALTER TABLE part_three_patrimony DROP FOREIGN KEY FK_AFC67A0C9A60D1F0');
        $this->addSql('ALTER TABLE patrimony DROP FOREIGN KEY FK_986416E23DA10740');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FCD81022C0');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FC36A17427');
        $this->addSql('ALTER TABLE evolution DROP FOREIGN KEY FK_420C28937B3C8E45');
        $this->addSql('ALTER TABLE future_income DROP FOREIGN KEY FK_5EB9C5E97B3C8E45');
        $this->addSql('ALTER TABLE part_one DROP FOREIGN KEY FK_B848A37A7B3C8E45');
        $this->addSql('ALTER TABLE part_six_recommendation DROP FOREIGN KEY FK_A4A72444D173940B');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FC235B6D1');
        $this->addSql('ALTER TABLE evolution DROP FOREIGN KEY FK_420C2893B0FDF16E');
        $this->addSql('ALTER TABLE future_income DROP FOREIGN KEY FK_5EB9C5E9B0FDF16E');
        $this->addSql('ALTER TABLE part_two DROP FOREIGN KEY FK_D3EEAFEDB0FDF16E');
        $this->addSql('ALTER TABLE total_annual_income DROP FOREIGN KEY FK_3BB45A54B0FDF16E');
        $this->addSql('ALTER TABLE part_two DROP FOREIGN KEY FK_D3EEAFED7F8E4905');
        $this->addSql('ALTER TABLE part_one DROP FOREIGN KEY FK_B848A37A8AFB327A');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FC328E815D');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E665D83CC1');
        $this->addSql('ALTER TABLE part_one DROP FOREIGN KEY FK_B848A37A6BF700BD');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6496BF700BD');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E662395FCED');
        $this->addSql('ALTER TABLE part_two_total_annual_income DROP FOREIGN KEY FK_B9EAAD0F81AC812C');
        $this->addSql('ALTER TABLE individual_form DROP FOREIGN KEY FK_9A4A67FC200761');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E6684A66610');
        $this->addSql('ALTER TABLE audit DROP FOREIGN KEY FK_9218FF79A76ED395');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CA76ED395');
        $this->addSql('DROP TABLE access');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE audit');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE children');
        $this->addSql('DROP TABLE collective_foresight');
        $this->addSql('DROP TABLE collective_retirement');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE credit_leasing');
        $this->addSql('DROP TABLE death_funds');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE drop_reaction');
        $this->addSql('DROP TABLE evolution');
        $this->addSql('DROP TABLE family_needs');
        $this->addSql('DROP TABLE financial_investment');
        $this->addSql('DROP TABLE financial_products');
        $this->addSql('DROP TABLE future_income');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE guarantee');
        $this->addSql('DROP TABLE guarantee_label');
        $this->addSql('DROP TABLE health_needs');
        $this->addSql('DROP TABLE individual_form');
        $this->addSql('DROP TABLE intelligence');
        $this->addSql('DROP TABLE maried');
        $this->addSql('DROP TABLE movable_heritage');
        $this->addSql('DROP TABLE movable_heritage_label');
        $this->addSql('DROP TABLE objective');
        $this->addSql('DROP TABLE part_five');
        $this->addSql('DROP TABLE part_five_individual_form');
        $this->addSql('DROP TABLE part_four');
        $this->addSql('DROP TABLE part_four_movable_heritage');
        $this->addSql('DROP TABLE part_one');
        $this->addSql('DROP TABLE part_one_children');
        $this->addSql('DROP TABLE part_seven');
        $this->addSql('DROP TABLE part_seven_documents');
        $this->addSql('DROP TABLE part_six');
        $this->addSql('DROP TABLE part_six_recommendation');
        $this->addSql('DROP TABLE part_three');
        $this->addSql('DROP TABLE part_three_patrimony');
        $this->addSql('DROP TABLE part_three_credit_leasing');
        $this->addSql('DROP TABLE part_two');
        $this->addSql('DROP TABLE part_two_guarantee');
        $this->addSql('DROP TABLE part_two_future_income');
        $this->addSql('DROP TABLE part_two_total_annual_income');
        $this->addSql('DROP TABLE patrimony');
        $this->addSql('DROP TABLE patrimony_label');
        $this->addSql('DROP TABLE preference');
        $this->addSql('DROP TABLE previous_financial_products');
        $this->addSql('DROP TABLE pro_status');
        $this->addSql('DROP TABLE recommendation');
        $this->addSql('DROP TABLE risk');
        $this->addSql('DROP TABLE salary');
        $this->addSql('DROP TABLE savings_plan');
        $this->addSql('DROP TABLE share_in_compagny');
        $this->addSql('DROP TABLE share_of_investment');
        $this->addSql('DROP TABLE state');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE thematic');
        $this->addSql('DROP TABLE total_annual_income');
        $this->addSql('DROP TABLE unplanned');
        $this->addSql('DROP TABLE user');
    }
}
